### ISSUE TITLE
Upload.url not building correctly

### ISSUE THREAD

**Issue by jvrana** [aquariumbio/aquarium#230]
Upload url is not being built correctly. The following code will produce a "bad component error."

```ruby
Upload.find_by_id(2).path # will not produce error
Upload.find_by_id(2).url # will produce "bad component error"
```

A minrep is located on the nursery server: **Bug Report Tests >> Upload url bug**

The error message is copied below: 
Error: bad component(expected host component): uwbiofab-nursery.s3-"us-west-2".amazonaws.com
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:593:in `check_host'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:634:in `host='
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:668:in `hostname='
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:187:in `initialize'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/http.rb:84:in `initialize'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:134:in `new'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:134:in `build'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/http.rb:62:in `build'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-1.7.1/lib/aws/s3/s3_object.rb:1287:in `build_uri'
/home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-1.7.1/lib/aws/s3/s3_object.rb:1172:in `url_for'

**Comment by klavins** [comment]
Is this still a bug?
