### ISSUE TITLE
aquarium-local hangs when batching operations

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/aquarium#620]
My aquarium-local instance hangs at `Loading operations ...` when I batch operations.

**Comment by dvnstrcklnd** [comment]
I can see that the status of the operations are changed to `scheduled` but the table of batched operations does not load in the manager tab.

**Comment by bjkeller** [comment]
Is this with a copy of the production database or with a database that you built from scratch?

**Comment by dvnstrcklnd** [comment]
Define "from scratch."

**Comment by dvnstrcklnd** [comment]
I'm adding stuff to the default database.

**Comment by dvnstrcklnd** [comment]
OK, I think this is happening:
```
app_1           | ActiveRecord::StatementInvalid (Mysql2::Error: Table 'production.view_job_assignments' doesn't exist: SHOW FULL FIELDS FROM `view_job_assignments`):
app_1           |   app/controllers/operations_controller.rb:148:in `block in manager_list'
app_1           |   app/controllers/operations_controller.rb:147:in `each'
app_1           |   app/controllers/operations_controller.rb:147:in `manager_list'
```

**Comment by bjkeller** [comment]
'from scratch' => from default database

**Comment by bjkeller** [comment]
need to look at default database and make sure has views

**Comment by dvnstrcklnd** [comment]
It doesn't.
